name: Terraform
on: push

jobs:
  check-format:
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v1
      - name: Checkout
        uses: actions/checkout@master
      - name: 'Terraform Format'
        run: terraform fmt -check -recursive

  check-checkov:
    name: Check checkov.io
    runs-on: bridgecrew/checkov
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: 'Checkov check'
        run: checkov -d ./
      - name: Run Checkov action
        uses: bridgecrewio/checkov-action@master
        with:
          directory: modules
          # skip_check: CKV_AWS_1 # optional: skip a specific check_id
          quiet: true # optional: display only failed checks
