name: Terraform
on: push

jobs:
  check-format:
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v1
      - name: Checkout
        uses: actions/checkout@master
      - name: 'Terraform Format'
        run: terraform fmt -check -recursive

  check-checkov:
    name: Check checkov.io
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Install checkov io
        run: sudo apt update && sudo apt install python3-pip && pip3 install setuptools checkov
      - name: Checkout
        uses: actions/checkout@master
      - name: Run Checkov checks
        run: checkov -d ./ --output github_failed_only

  validate-examples:
    name: Validate examples
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: examples
    steps:
      - uses: hashicorp/setup-terraform@v1
      - name: Checkout
        uses: actions/checkout@master
      - name: Check examples
        env:
          EXAMPLES: simple external-bucket select-region organization/master organization/member
        run: |
          for EXAMPLE in ${EXAMPLES}
          do
            echo "Validating $EXAMPLE"...
            cd $EXAMPLE && terraform init && terraform validate && cd -
          done
